# -*- coding: utf-8 -*-
"""Copia de Análisis de sentimiento con BERT y LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rRvs7oTjkVBrMVhBHrIhYw6HLrWN1H7u
"""

import pandas as pd

# Ruta del archivo original
csv_path = '/content/training.1600000.processed.noemoticon.csv'
clean_path = '/content/cleaned.csv'

# Limpiar líneas con comillas sin cerrar
with open(csv_path, 'r', encoding='latin-1') as infile, open(clean_path, 'w', encoding='latin-1') as outfile:
    for line in infile:
        if line.count('"') % 2 == 0:  # Solo escribir líneas con comillas balanceadas
            outfile.write(line)

# Leer el archivo limpio
df = pd.read_csv(
    clean_path,
    header=None,
    encoding='latin-1',
    low_memory=False
)

# Asignar nombres de columnas
df.columns = ['target', 'ids', 'date', 'flag', 'user', 'text']
df = df[['target', 'text']]

# Mostrar resultados
from IPython.display import display
display(df.head())
display(df.tail())
print(f"✅ Total de filas cargadas correctamente: {len(df):,}")

import re

def limpiar_texto(text):
    text = re.sub(r"http\S+", "", text)         # Eliminar URLs
    text = re.sub(r"@\w+", "", text)            # Eliminar menciones
    text = re.sub(r"#\w+", "", text)            # Eliminar hashtags
    text = re.sub(r"[^A-Za-zÀ-ÿñÑ\s]", "", text) # Eliminar símbolos
    text = text.lower()
    return text

df['clean_text'] = df['text'].apply(limpiar_texto)

# Filtrar textos que tienen solo letras, espacios y tildes
import re

def texto_valido(text):
    return not bool(re.search(r"[^a-zA-ZÀ-ÿñÑ\s]", text))

# Aplicar filtro
df = df[df['clean_text'].apply(texto_valido)].reset_index(drop=True)

# 1. Eliminar textos vacíos
df = df[df['clean_text'].str.strip() != '']

# 2. Eliminar textos con caracteres no deseados
def texto_valido(text):
    return not bool(re.search(r"[^a-zA-ZÀ-ÿñÑ\s]", text))

df = df[df['clean_text'].apply(texto_valido)].reset_index(drop=True)

# Eliminar filas con valores NaN en la columna 'clean_text'
df = df.dropna(subset=['clean_text'])

# Reiniciar los índices para mantener el DataFrame limpio
df = df.reset_index(drop=True)

# Conteo de valores nulos por columna
print(df.isnull().sum())

def texto_valido(text):
    return not bool(re.search(r"[^a-zA-ZÀ-ÿüÜñÑ\s]", text))

df = df[df['clean_text'].apply(texto_valido)].reset_index(drop=True)

# Revisar ejemplos que aún puedan tener caracteres sospechosos
import re

ejemplos_raros = df[df['clean_text'].apply(lambda x: bool(re.search(r"[^a-zà-ÿñ\s]", x)))]
print("Filas con caracteres especiales restantes:", len(ejemplos_raros))

# Mostrar algunos si existen
if not ejemplos_raros.empty:
    display(ejemplos_raros.sample(5))

# Ver textos vacíos
vacios = df[df['clean_text'].str.strip() == '']
print("Textos vacíos:", len(vacios))

import pandas as pd
import torch
from tqdm.auto import tqdm
from transformers import BertTokenizerFast
import warnings
warnings.filterwarnings("ignore")


tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')

def tokenizar_en_bloques(textos, batch_size=10000, max_len=128):
    input_ids = []
    attention_masks = []

    for i in tqdm(range(0, len(textos), batch_size), desc="Tokenizando"):
        batch = textos[i:i+batch_size]
        tokens = tokenizer(
            batch,
            padding='max_length',
            truncation=True,
            max_length=max_len,
            return_tensors="pt"
        )
        input_ids.append(tokens['input_ids'])
        attention_masks.append(tokens['attention_mask'])

    return {
        'input_ids': torch.cat(input_ids, dim=0),
        'attention_mask': torch.cat(attention_masks, dim=0)
    }

# Ejecutar tokenización
inputs = tokenizar_en_bloques(df['clean_text'].tolist())

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer_lstm = Tokenizer(num_words=10000, oov_token="<OOV>")
tokenizer_lstm.fit_on_texts(df['clean_text'])
sequences = tokenizer_lstm.texts_to_sequences(df['clean_text'])
padded_sequences = pad_sequences(sequences, padding='post', maxlen=50)

from sklearn.model_selection import train_test_split

X = padded_sequences  # Entradas tokenizadas
y = df['target'].astype(int)  # Asegúrate de que las etiquetas sean numéricas

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Entrenamiento:", X_train.shape, "Test:", X_test.shape)

inputs['input_ids'].shape
inputs['attention_mask'].shape

print(padded_sequences[:1])     # Primera secuencia tokenizada y padded
print(len(tokenizer_lstm.word_index))  # Tamaño del vocabulario

print(X_train.shape, X_test.shape)

for i in range(3):
    print("Texto limpio:", df['clean_text'].iloc[i])
    print("Secuencia:", padded_sequences[i])
    print("Etiqueta:", df['target'].iloc[i])
    print("-----")

!pip install transformers datasets scikit-learn

# 🛑 Asegurarse de usar solo clases que el modelo entiende: 0 = negativo, 1 = positivo
df = df[df['target'].isin([0, 4])].copy()
df['target'] = df['target'].map({0: 0, 4: 1})

from transformers import AutoTokenizer, AutoModelForSequenceClassification

modelo_nombre = "distilbert-base-uncased-finetuned-sst-2-english"

tokenizer = AutoTokenizer.from_pretrained(modelo_nombre)
model = AutoModelForSequenceClassification.from_pretrained(modelo_nombre)

import torch

# Ejemplo con los primeros 10 textos
texts = df['clean_text'][:10].tolist()

# Tokenizar
tokens = tokenizer(texts, padding=True, truncation=True, return_tensors="pt")

# Inferencia
with torch.no_grad():
    outputs = model(**tokens)

logits = outputs.logits
predicciones = torch.argmax(logits, dim=1).numpy()

!pip install transformers==4.41.0 sentence-transformers --upgrade

print(df.columns)

import torch
import time
import gc
from tqdm.auto import tqdm
from torch.utils.data import DataLoader, TensorDataset, random_split
from sklearn.metrics import accuracy_score, f1_score, classification_report
from transformers import BertTokenizerFast, BertForSequenceClassification
from torch.optim import AdamW

# ⚙️ Configuración segura
MAX_LEN = 64
BATCH_SIZE = 8
NUM_EPOCHS = 2
LEARNING_RATE = 2e-5
DEVICE = torch.device("cpu")  # 🔒 Evita reinicio forzando CPU

# 🧠 Tokenizador
tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')

# 🔁 Tokenización
def tokenizar_textos(textos):
    print("🔠 Tokenizando textos...")
    tokens = tokenizer(
        textos.tolist(),
        padding='max_length',
        truncation=True,
        max_length=MAX_LEN,
        return_tensors="pt"
    )
    return tokens['input_ids'], tokens['attention_mask']

# 🧪 Muestra segura del dataset
df_sample = df.sample(n=3000, random_state=42).copy()
df_sample['label'] = df_sample['target'].apply(lambda x: 1 if x == 4 else 0)  # ✅ usar 'target' como sentimiento

# 📦 Preparar tensores
input_ids, attention_mask = tokenizar_textos(df_sample['clean_text'])  # ✅ usar 'clean_text'
labels = torch.tensor(df_sample['label'].values)

# 📚 Dataset y división
dataset = TensorDataset(input_ids, attention_mask, labels)
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)

# 🧱 Modelo
print("📦 Cargando modelo BERT...")
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)
model.to(DEVICE)

# 🚀 Optimización
optimizer = AdamW(model.parameters(), lr=LEARNING_RATE)

# 🎯 Entrenamiento
print("🚀 Iniciando entrenamiento...")
for epoch in range(NUM_EPOCHS):
    model.train()
    total_loss = 0
    for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
        input_ids, attention_mask, labels = [x.to(DEVICE) for x in batch]
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        total_loss += loss.item()
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        gc.collect()  # 🧹 Limpieza automática
    avg_loss = total_loss / len(train_loader)
    print(f"🔁 Epoch {epoch+1} - Loss promedio: {avg_loss:.4f}")

# 📊 Evaluación
print("📊 Evaluando modelo...")
model.eval()
preds, true_labels = [], []

with torch.no_grad():
    for batch in val_loader:
        input_ids, attention_mask, labels = [x.to(DEVICE) for x in batch]
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        preds.extend(torch.argmax(logits, dim=1).cpu().numpy())
        true_labels.extend(labels.cpu().numpy())

# 📈 Métricas
print("🕒 Evaluación completada")
print("Accuracy:", accuracy_score(true_labels, preds))
print("F1 Score:", f1_score(true_labels, preds, average="weighted"))
print("📄 Reporte de Clasificación:")
print(classification_report(true_labels, preds))

# 🧹 Limpieza final
del model, train_loader, val_loader
gc.collect()

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional

# ✅ 1. Asegurarse de que las etiquetas están en formato correcto (0 y 1, tipo float)
y_train = np.where(y_train == 4, 1, y_train).astype("float32")
y_test = np.where(y_test == 4, 1, y_test).astype("float32")

# ✅ 2. Definir los parámetros principales del modelo
vocab_size = len(tokenizer_lstm.word_index) + 1
embedding_dim = 64
max_len = 50  # Ya que así fueron padding tus secuencias

# ✅ 3. Construir el modelo LSTM
model_lstm = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim),
    Bidirectional(LSTM(64)),
    Dropout(0.3),
    Dense(1, activation='sigmoid')  # Binaria
])

# ✅ 4. Compilar el modelo
model_lstm.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# ⚠️ Usamos solo una muestra para que entrene rápido y sin consumir mucha RAM
N = 20000  # Puedes aumentarlo si tienes recursos

# 🏋️ Entrenamiento
history = model_lstm.fit(
    X_train[:N],
    y_train[:N],
    epochs=3,
    batch_size=256,
    validation_split=0.1,
    verbose=1
)

# 🧪 Evaluación final sobre datos de test (subconjunto)
loss, acc = model_lstm.evaluate(X_test[:5000], y_test[:5000], verbose=0)
print(f"🧪 Test Accuracy: {acc:.4f} - Loss: {loss:.4f}")

import plotly.graph_objects as go

fig = go.Figure(data=[
    go.Bar(name='BERT', x=['Accuracy', 'F1 Score'], y=[0.738, 0.735], marker_color='rgb(31, 119, 180)'),
    go.Bar(name='LSTM', x=['Accuracy', 'F1 Score'], y=[0.761, 0.76], marker_color='rgb(255, 127, 14)')
])

fig.update_layout(
    title='Comparación de rendimiento: BERT vs LSTM',
    yaxis=dict(title='Puntaje'),
    barmode='group',
    template='plotly_white'
)

fig.show()

fig = go.Figure()

fig.add_trace(go.Bar(
    name='Entrenamiento',
    x=['BERT', 'LSTM'],
    y=[0, 120],  # segundos (LSTM tardó ~2 min)
    marker_color='rgba(26, 118, 255, 0.7)'
))

fig.add_trace(go.Bar(
    name='Inferencia',
    x=['BERT', 'LSTM'],
    y=[105, 5],
    marker_color='rgba(255, 153, 51, 0.7)'
))

fig.update_layout(
    title='Tiempos de procesamiento por modelo',
    yaxis_title='Segundos',
    barmode='group',
    template='plotly_dark'
)

fig.show()

"""🔍 ¿Por qué no se ve el entrenamiento de BERT en el gráfico?
Porque no se entreno BERT desde cero ni se hizo fine-tuning. Se uso el modelo bert-base-uncased-finetuned-sst-2-english, que ya viene completamente entrenado en sentimientos generales. Solo se hizo inferencias sobre tus datos, sin modificar sus pesos.

🔹 Es decir:
Entrenamiento de BERT: ⛔ no ocurrió, por eso aparece como 0 s o ni aparece.

Entrenamiento de LSTM: ✅ Sí lo entrenaste, y por eso su tiempo está reflejado.
"""